# Generated by Django 4.2.2 on 2023-07-25 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=30)),
                ('task_status', models.BooleanField(default=False)),
                ('tasks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.project')),
            ],
        ),
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtask', models.CharField(max_length=30)),
                ('subtask_status', models.BooleanField(default=False)),
                ('subtasks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.task')),
            ],
        ),
    ]
