# Generated by Django 4.2.2 on 2023-08-01 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_task_subtask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtask',
            old_name='subtasks',
            new_name='tasks',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='tasks',
            new_name='project',
        ),
    ]
