# Generated by Django 4.2.2 on 2023-09-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_subtask_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multipleimages',
            name='images',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
