# Generated by Django 4.2.2 on 2023-10-06 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_meetings'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetings',
            name='sbtsk',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='planner.subtask'),
            preserve_default=False,
        ),
    ]
