# Generated by Django 4.2.2 on 2023-10-06 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_meetings_sbtsk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetings',
            name='sbtsk',
        ),
    ]
