# Generated by Django 4.2.2 on 2023-11-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0008_remove_meetings_sbtsk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='subtask_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.BooleanField(default=True),
        ),
    ]
