# Generated by Django 4.2.2 on 2023-11-01 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0009_alter_subtask_subtask_status_alter_task_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
        migrations.AddField(
            model_name='project',
            name='project_status',
            field=models.BooleanField(default=False),
        ),
    ]
