# Generated by Django 4.2.2 on 2023-11-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0012_alter_project_project_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='deadline',
        ),
        migrations.AddField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meetings',
            name='meeting_status',
            field=models.CharField(choices=[('active', 'active'), ('completed', 'completed')], default='active', max_length=10),
        ),
    ]
