# Generated by Django 4.2.2 on 2023-12-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0013_remove_subtask_deadline_task_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='change_task_status',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
