# Generated by Django 4.2.2 on 2023-12-14 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0014_task_change_task_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='change_task_status',
        ),
        migrations.AddField(
            model_name='meetings',
            name='completed_status_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='subtask',
            name='completed_status_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='completed_status_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
