# Generated by Django 4.2.2 on 2024-02-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0016_alter_meetings_completed_status_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_to_send', models.CharField(blank=True, max_length=6, null=True)),
            ],
        ),
    ]
