# Generated by Django 4.2.2 on 2024-02-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0018_passwordtorecover_delete_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordtorecover',
            name='time_of_gen_password',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
